### ISSUE TITLE
Skip components with undefined propTypes member

### ISSUE THREAD

**Issue by pellebjerkestrand** [Creuna-Oslo/prop-types-csharp#58]
If one defines a component without the `propTypes` member, class generation errors out.

I expect these components to be skipped instead of having to `<ComponentName>.propTypes = {};` all over the place.

**Comment by asbjornh** [comment]
I agree that it shouldn’t crash. I’ll fix it tomorrow. If you have so many components without proptypes that it causes issues this probably highlights a config problem or a code smell though. The exclude option to the webpack plugin may be useful (like excluding all static site components)

**Comment by pellebjerkestrand** [comment]
I had one component like that 😅.

**Comment by asbjornh** [comment]
So not "all over the place" then :)

**Comment by asbjornh** [comment]
Hm ok so you're probably referring to this deliberately thrown error:

```
ERROR in C# class generator plugin

<path to component>
PropTypes not found
```

The rationale behind this error stems from the fact that the generator does not keep track of what components depend on what other components in order to be buildable. The generator therefore assumes that every component is needed in order to build the view models.

Of course, missing classes would eventually be caught by the build server (assuming that it exists and that it's hooked up to show build statuses on PRs), but IMO it's nice to get this information sooner rather than maybe later.

There's a mechanism for explicitly excluding a component from class generation:

```js
MyComponent.propTypesMeta = "exclude";
```

I do think that excluding components from class generation should be explicit, and I'm tempted to mark this as "won't fix".

**Comment by asbjornh** [comment]
That said, though, I'm not sure that the above exclude actually works without the propTypes literal. It definitely should and I'll make sure it does.

**Comment by asbjornh** [comment]
> That said, though, I'm not sure that the above `"exclude"` actually works without the propTypes literal. It definitely should and I'll make sure it does.

Yeah, it doesn't currently work. But it will work in `1.0.2` which should be out any minute now.

**Comment by asbjornh** [comment]
I'm gonna close this. If this really poses a legitimate issue I think a better approach would be to add a `strict` option to the plugin (defaulting to `true`). If this is needed, a new issue can be created
